

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "4147:8080"
    environment:
      - BASE_URL=http://localhost:4147/
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    volumes:
      - /home/pesquisajson/settings.yml:/etc/searxng/settings.yml:ro
