use_default_settings: true

server:
  secret_key: "badb6e6e43bb104ff795b581e68068b49e7909833df33466b139939b4d1cace0"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  public_instance: false

ui:
  theme: oscar

general:
  instance_name: "SearXNG do Sérgio"
  contact_url: "mailto:seuemail@dominio.com"
  enable_metrics: true

search:
  safe_search: 1
  autocomplete: "duckduckgo"

engines:
  - name: google
    disabled: true
  - name: bing
    disabled: true
  - name: qwant
    disabled: false

search:
  formats:
    - html
    - json
